#!/bin/bash -l

################################################################################
#Script Name: salmon_ti.pbs
#Desription : create transcriptome indices from cdna fasta
#Args       : None 
#Author     : Georgia Doing
#Date       : 12-18-20
#Email      : Georgia.Doing.GR@Dartmouth.edu
################################################################################

#PBS -q default
# #PBS -A NCCC
#PBS -N sal_t_idx
#PBS -l walltime=00:30:00
#PBS -l nodes=1:ppn=1
#PBS -m bea
#PBS -M Georgia.Doing.GR@Dartmouth.edu
#PBS -j oe
#PBS -e oe
#PBS -o oe



cd $PBS_O_WORKDIR

conda activate salmon

salmon index -t ../t_indxs/pao1_cdna.fa.gz -i ..//t_indxs/pao1_cdna_k15 -k 15
salmon index -t ../t_indxs/pa14_cdna.fa.gz -i ../t_indxs/pa14_cdna_k15 -k 15


